name: actionlint
on:
  workflow_call:

jobs:
  workflow_syntax:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Set up actionlint
        shell: bash
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          echo "$(brew --prefix)/bin" >> "$GITHUB_PATH"
          brew install actionlint shellcheck
          # Setting `shell: /bin/bash` prevents shellcheck from running on
          # those steps, so let's change them to `shell: bash` for linting.
          sed -i 's:/bin/bash -e {0}:bash:' .github/workflows/*.y*ml
          # The JSON matcher needs to be accessible to the container host.
          cp "$(brew --repository)/.github/actionlint-matcher.json" "$HOME"
          echo "::add-matcher::$HOME/actionlint-matcher.json"
      - run: actionlint