name: Apidoc
on:
  workflow_call:

jobs:
  build_apidoc:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/smillerdev/phpdraft:main
    permissions:
      packages: read
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Detect API docs
        id: detect
        run: |
          echo "docs=$(find docs/apidoc/ -type d -maxdepth 1 -exec basename {} \; | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Build Frontend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'frontend') }}
        run: |
          install -d build/apidoc/frontend
          phpdraft --file docs/apidoc/frontend/index.apib \
                   --sort Structures \
                   --openapi build/apidoc/frontend/openapi.json > build/apidoc/frontend/index.html

      - name: Build Backend API documentation
        if: ${{ contains(steps.detect.outputs.docs, 'backend') }}
        run: |
          install -d build/apidoc/backend
          phpdraft --file docs/apidoc/backend/index.apib \
                   --sort Structures \
                   --openapi build/apidoc/backend/openapi.json > build/apidoc/backend/index.html

      - uses: actions/upload-artifact@v4
        with:
          name: API-documentation
          path: build/apidoc
          if-no-files-found: error
          retention-days: 15
