name: Apidoc
on:
  workflow_call:
    inputs:
      amazon_region:
        required: false
        default: us-east-1
        type: string
    secrets:
      amazon_role:
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy_s3:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - name: Download API doc
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4.3.0
        with:
          name: API-documentation

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@b47578312673ae6fa5b5096b330d9fbac3d116df # v4.2.1
        with:
          aws-region: ${{ inputs.amazon_region }}
          role-to-assume: ${{ secrets.amazon_role }}

      - name: Generate project name
        shell: bash
        id: generate-project
        run: |
          PROJECT=$(echo '${{ github.repository	}}' | sed 's|${{ github.repository_owner }}/||')
          echo "project=${PROJECT,,}" >> "$GITHUB_OUTPUT"

      - name: Detect API docs
        id: detect
        run: |
          echo "docs=$(find . -type d -maxdepth 1 -exec basename {} \; | tr '\n' ' ')" >> "$GITHUB_OUTPUT"
          cat "$GITHUB_OUTPUT"

      - name: Deploy Backend API doc to S3
        if: ${{ contains(steps.detect.outputs.docs, 'backend') }}
        env:
          PROJECT: ${{ steps.generate-project.outputs.project }}
        run: aws s3 cp --recursive --force --acl public-read backend/ "s3://move-$PROJECT-apidoc/backend"

      - name: Deploy Frontend API doc to S3
        if: ${{ contains(steps.detect.outputs.docs, 'frontend') }}
        env:
          PROJECT: ${{ steps.generate-project.outputs.project }}
        run: aws s3 cp --recursive --force --acl public-read frontend/ "s3://move-$PROJECT-apidoc/frontend"
