name: Functional Tests
on:
  workflow_call:
    inputs:
      tests-path:
        required: false
        type: string
        default: 'tests/functional/testsuites/'
      php-extensions:
        required: false
        type: string
        default: ''
      php-ini-settings:
        required: false
        type: string
        default: ''
      php-version:
        required: false
        type: string
        default: '8.3'
    secrets:
      COMPOSER_AUTH:
        required: false
      SLACK_WEBHOOK_URL:
        required: false

env:
  SLACK_SEND_EVENTS: '["push", "schedule"]'

jobs:
  functional-tests:
    runs-on: ubuntu-latest
    name: Functional Tests
    timeout-minutes: 15
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: true

      - name: Set up PHP
        uses: shivammathur/setup-php@f3e473d116dcccaddc5834248c87452386958240 # 2.37.2
        with:
          php-version: ${{ inputs.php-version }}
          extensions: ${{ inputs.php-extensions }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache composer dependencies
        id: composer-cache
        uses: actions/cache@27d5ce7f107fe9357f9df03efb73ab90386fccae # v5.0.5
        with:
          path: |
            ${{ github.workspace }}/vendor
          key: ${{ runner.os }}-php-${{ inputs.php-version }}-${{ hashFiles('composer.json', 'composer.lock') }}

      - name: Install dependencies
        run: composer install
        env:
          COMPOSER_AUTH: ${{ secrets.COMPOSER_AUTH }}

      - name: Setup Bats and bats libs
        id: setup-bats
        uses: bats-core/bats-action@77d6fb60505b4d0d1d73e48bd035b55074bbfb43 # 4.0.0

      - name: Run setup
        run: ./support/setup.sh

      - name: Set config overrides
        run: |
          cp -a config/conf.application.local.inc.php.sample config/conf.application.local.inc.php
          sed -i "s|{{ environment }}|ci|" config/conf.application.local.inc.php

      - name: Functional tests
        shell: bash
        env:
          BATS_LIB_PATH: ${{ steps.setup-bats.outputs.lib-path }}
          TERM: xterm
          TEST_PATH: ${{ inputs.tests-path }}
        run: bats --recursive "$TEST_PATH" --print-output-on-failure --filter-tags '!mariadb:true' --report-formatter junit --output "$PWD"

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@d0a4676d0e0b938bc201470d88276b7c74c712b3 # v2.24.0
        if: always()
        with:
          check_run: false
          files: |
            report.xml

      - name: Post a message in a channel
        uses: slackapi/slack-github-action@45a88b9581bfab2566dc881e2cd66d334e621e2c # v3.0.3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() && contains(fromJSON(env.SLACK_SEND_EVENTS), github.event_name) && env.SLACK_WEBHOOK_URL != '' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*${{ github.repository }} (${{ github.ref_name }})*: Functional Tests ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "*${{ github.repository }} (${{ github.ref_name }})*: Functional Tests ${{ job.status }}\nURL: ${{ github.event.pull_request.html_url || format('https://github.com/{0}/commit/{1}', github.repository, github.sha) }}\nWorkflow Run: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
