name: PHP Tests
on:
  workflow_call:
    inputs:
      phpstan-level:
        required: false
        type: string
        default: 4
      codestyle:
        required: false
        type: string
        default: Stellr
      codestyle-repo:
        required: false
        type: string
        default: 'move-backend/stellr-coding-standard'
      codestyle-branch:
        required: false
        type: string
        default: stellr
      minimum-php-version:
        required: false
        type: string
        default: '8.1'
      stable-php-versions:
        required: false
        type: string
        default: '["8.1"]'
      experimental-php-versions:
        required: false
        type: string
        default: '["8.2", "8.3"]'
      minimum-phpunit-version:
        required: false
        type: string
        default: '9.5.x'
      allow-style-failures:
        required: false
        type: boolean
        default: false
      allow-phpstan-failures:
        required: false
        type: boolean
        default: false
      allow-sonarqube-failures:
        required: false
        type: boolean
        default: false
      phpcs-whitelist:
        required: false
        type: string
        default: ''
      sonar-host-url:
        required: false
        type: string
        default: 'https://whale.moveagency.com'
      php-extensions:
        required: false
        type: string
        default: 'autoload_psr-pprkut/autoload-psr@0.2.0'
    secrets:
      SSH_PRIVATE_KEY_FOR_CLONING_NONPUBLIC_BACKEND_GIT_REPOSITORIES:
        required: true
      SONAR_TOKEN:
        required: false
      SLACK_WEBHOOK_URL:
        required: false

jobs:
  generate-matrix:
    name: Generate matrix for phpunit
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Set matrix for build
        id: set-matrix
        env:
          STABLE_VERSIONS: ${{ inputs.stable-php-versions }}
          EXPERIMENTAL_VERSIONS: ${{ inputs.experimental-php-versions }}
        run: |
          JSON=$(jq --null-input --arg stable "$STABLE_VERSIONS" --arg experimental "$EXPERIMENTAL_VERSIONS" '{"php-versions": $stable | fromjson, "experimental": [ false ], "include":[ $experimental | fromjson | .[] as $version | {"php-versions": $version, "experimental": true} ]} | tostring')
          echo "matrix=$JSON" >> "$GITHUB_OUTPUT"

  phpunit:
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    name: "PHP-${{ matrix.php-versions }}: PHPUnit"
    needs: generate-matrix
    strategy:
      matrix: ${{ fromJson(fromJson(needs.generate-matrix.outputs.matrix)) }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Cache decomposer dependencies
        id: cache-decomposer
        uses: actions/cache@v4
        with:
          path: | 
            ${{ github.workspace }}/vendor
            ${{ github.workspace }}/decomposer.autoload.inc.php
          key: ${{ runner.os }}-${{ hashFiles('decomposer.json') }}
          restore-keys: 
            ${{ runner.os }}-

      - name: Decomposer checkout
        uses: actions/checkout@v4
        with:
            repository: 'move-backend/decomposer'

            # Relative path under $GITHUB_WORKSPACE to place the repository
            path: 'decomposer'
            persist-credentials: false

      - if: ${{ steps.cache-decomposer.outputs.cache-hit != 'true' }}
        name: Prepare decomposer target directory
        run: mkdir -p "$GITHUB_WORKSPACE/vendor"

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: phpunit:${{ inputs.minimum-phpunit-version }}
          extensions: ${{ inputs.php-extensions }}
          ini-values: include_path='.:/usr/share/php:$GITHUB_WORKSPACE/vendor'

      - name: Setup problem matchers for PHP
        run: echo "::add-matcher::${{ runner.tool_cache }}/php.json"

      - name: Configure ssh keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_FOR_CLONING_NONPUBLIC_BACKEND_GIT_REPOSITORIES }}

      - name: Install dependencies
        run: DECOMPOSER_TARGET_DIR="$GITHUB_WORKSPACE/vendor" decomposer/bin/decomposer install

      - name: Run PHPunit
        run: phpunit --configuration tests/phpunit.xml

      - name: Summarize Tests
        uses: test-summary/action@v2
        if: failure() || success()
        with:
          paths: build/logs/junit.xml
          show: fail

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: phpunit-logs-${{ matrix.php-versions }}
          path: build/logs/
      - name: Post a message in a channel
        uses: slackapi/slack-github-action@v2.0.0
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: ${{ failure() && env.SLACK_WEBHOOK_URL != '' }}
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            text: "*GitHub Action build result*: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
            blocks:
              - type: "section"
                text:
                  type: "mrkdwn"
                  text: "GitHub Action build result: ${{ job.status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"

  phpcs:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.allow-style-failures }}
    name: "PHPCS"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Codestyle checkout
        uses: actions/checkout@v4
        with:
            repository: ${{ inputs.codestyle-repo }}
            ref: ${{ inputs.codestyle-branch }}

            # Clone submodules recursively. `true` should be enough, but better be safe
            submodules: 'recursive'

            # Relative path under $GITHUB_WORKSPACE to place the repository
            path: 'codestyle'
            persist-credentials: false

      - name: Install dependencies
        if: ${{ hashFiles('codestyle/composer.json') != '' }}
        working-directory: 'codestyle'
        run: composer install

      - name: Setup PHPCS
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.minimum-php-version }}
          tools: cs2pr, phpcs

      - name: Run PHPCS
        run: |
          BOOTSTRAP=$([ -e "$GITHUB_WORKSPACE/codestyle/bootstrap.php" ] && echo "--bootstrap=$GITHUB_WORKSPACE/codestyle/bootstrap.php" || echo '')
          export BOOTSTRAP
          SLEVOMAT=$([ -d "$GITHUB_WORKSPACE/codestyle/third-party/slevomat/" ] && echo "--runtime-set installed_paths $GITHUB_WORKSPACE/codestyle/third-party/slevomat/" || echo '')
          export SLEVOMAT
          phpcs --report-full \
                --report-checkstyle=checkstyle.xml \
                "$SLEVOMAT" \
                "$BOOTSTRAP" \
                --standard="$GITHUB_WORKSPACE/codestyle/${{ inputs.codestyle }}" \
                --ignore=locate\.* \
                ${{ inputs.phpcs-whitelist }} \
                src/

      - name: Convert checkstyle output to github style
        if: always()
        run: cs2pr ./checkstyle.xml

  phpstan:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.allow-phpstan-failures }}
    name: "PHPStan"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Cache decomposer dependencies
        id: cache-decomposer
        uses: actions/cache@v4
        with:
          path: | 
            ${{ github.workspace }}/vendor
            ${{ github.workspace }}/decomposer.autoload.inc.php
          key: ${{ runner.os }}-${{ hashFiles('decomposer.json') }}
          restore-keys: 
            ${{ runner.os }}-

      - name: Decomposer checkout
        uses: actions/checkout@v4
        with:
            repository: 'move-backend/decomposer'

            # Relative path under $GITHUB_WORKSPACE to place the repository
            path: 'decomposer'
            persist-credentials: false

      - if: ${{ steps.cache-decomposer.outputs.cache-hit != 'true' }}
        name: Prepare decomposer target directory
        run: mkdir -p "$GITHUB_WORKSPACE/vendor"

      - name: Setup PHPStan
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ inputs.minimum-php-version }}
          tools: phpstan
          extensions: autoload_psr-pprkut/autoload-psr@0.2.0
          ini-values: include_path='.:/usr/share/php:$GITHUB_WORKSPACE/vendor'

      - name: Configure ssh keys
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: |
            ${{ secrets.SSH_PRIVATE_KEY_FOR_CLONING_NONPUBLIC_BACKEND_GIT_REPOSITORIES }}

      - name: Install dependencies
        run: DECOMPOSER_TARGET_DIR="$GITHUB_WORKSPACE/vendor" decomposer/bin/decomposer install

      - name: Run PHPStan
        env:
          PHPSTAN_LEVEL: ${{ inputs.phpstan-level }}
        run: phpstan analyze src --level "$PHPSTAN_LEVEL" --configuration tests/phpstan.neon.dist --autoload-file tests/phpstan.autoload.inc.php
  sonarqube:
    runs-on: ubuntu-latest
    continue-on-error: ${{ inputs.allow-sonarqube-failures }}
    name: SonarQube
    needs: [phpunit]
    steps:
      - name: Determine variables
        id: variables
        run: |
          OWNER="${{ github.repository_owner }}"
          REPO="${{ github.repository	}}"
          ACCOUNT_SLUG=${OWNER/move-/}
          echo "account=${ACCOUNT_SLUG^^}" >> "$GITHUB_OUTPUT"
          echo "project=${REPO/$OWNER\//}" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Download logs
        uses: actions/download-artifact@v4
        with:
          name: phpunit-logs-${{ inputs.minimum-php-version }}
          path: ${{ github.workspace }}/build/logs

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_HOST_URL: ${{ inputs.sonar-host-url }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        if: ${{ env.SONAR_TOKEN != '' }}
        with:
          args: >
            -Dsonar.projectKey=${{ steps.variables.outputs.account }}:backend:${{ steps.variables.outputs.project }}
            -Dsonar.projectName=${{ steps.variables.outputs.project }}
            -Dsonar.php.tests.reportPath=build/logs/junit.xml
            -Dsonar.php.coverage.reportPaths=build/logs/clover.xml
            -Dsonar.plugins.downloadOnlyRequired=true
            -Dsonar.verbose=true
