name: PHPUnit config check
on:
  workflow_call:

jobs:
  phpunit-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: framna-nl-backend/actions/phpunit-config@main
