name: PHPUnit config check
on:
  workflow_call:

jobs:
  phpunit-config:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - uses: framna-nl-backend/actions/phpunit-config@main
