name: Spellcheck
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: 'typos.toml'
      required:
        type: boolean
        default: false

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: ${{ !inputs.required }}
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@a9ccf76b53d1ace194871d216f9ff058599a86db # v1.35.1
        with:
          config: ${{ inputs.config }}
