name: Spellcheck
on:
  workflow_call:
    inputs:
      config:
        required: false
        type: string
        default: 'typos.toml'
      required:
        type: boolean
        default: false

jobs:
  typos:
    runs-on: ubuntu-latest
    continue-on-error: ${{ !inputs.required }}
    name: "Spellcheck (typos)"
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: typos-action
        uses: crate-ci/typos@master
        with:
          config: ${{ inputs.config }}
